### ISSUE TITLE
Update for Apple Magic Keyboard?

### ISSUE THREAD

**Issue by dtosoff** [samartzidis/WinA1314#8]
Hi,

Any chance you'll be patching so that this drive can be used for the apple magic keyboard?

I'm happy to provide hardware IDs, etc, if you need any details.

Cheers,
David

**Comment by Adwerk** [comment]
+1 on this one. Would be very awesome.

And thanks for the work you put into Wina1314.

**Comment by agotfred** [comment]
I tried adding the hardware IDs and compiling the driver. I could still not get my magic keyboard to work. 

I am not sure we will have a chance to get a working update unless samartzidis becomes an user of the new keyboard himself.

**Comment by samartzidis** [comment]
No it is impossible to get the new Magic Keyboard working with the WinA1314 tricks but I have just released a new project (a someone gave me the Magic keyboard as a gift this Christmas and I wanted to get it working) that specifically addresses the Magic Keyboard (plus the old A1314 one:)). Hosted at: https://github.com/samartzidis/WinAppleKey. You may want to have a look.
